export const countriesWithFlags = [
  { title: 'Afganistán', cdn: 'https://flagcdn.com/af.svg' },
  { title: 'Albania', cdn: 'https://flagcdn.com/al.svg' },
  { title: 'Alemania', cdn: 'https://flagcdn.com/de.svg' },
  { title: 'Andorra', cdn: 'https://flagcdn.com/ad.svg' },
  { title: 'Angola', cdn: 'https://flagcdn.com/ao.svg' },
  { title: 'Anguila', cdn: 'https://flagcdn.com/ai.svg' },
  { title: 'Antártida', cdn: 'https://flagcdn.com/aq.svg' },
  { title: 'Antigua y Barbuda', cdn: 'https://flagcdn.com/ag.svg' },
  { title: 'Arabia Saudita', cdn: 'https://flagcdn.com/sa.svg' },
  { title: 'Argelia', cdn: 'https://flagcdn.com/dz.svg' },
  { title: 'Argentina', cdn: 'https://flagcdn.com/ar.svg' },
  { title: 'Armenia', cdn: 'https://flagcdn.com/am.svg' },
  { title: 'Aruba', cdn: 'https://flagcdn.com/aw.svg' },
  { title: 'Australia', cdn: 'https://flagcdn.com/au.svg' },
  { title: 'Austria', cdn: 'https://flagcdn.com/at.svg' },
  { title: 'Azerbaiyán', cdn: 'https://flagcdn.com/az.svg' },
  { title: 'Bahamas', cdn: 'https://flagcdn.com/bs.svg' },
  { title: 'Bahrein', cdn: 'https://flagcdn.com/bh.svg' },
  { title: 'Bangladesh', cdn: 'https://flagcdn.com/bd.svg' },
  { title: 'Barbados', cdn: 'https://flagcdn.com/bb.svg' },
  { title: 'Bélgica', cdn: 'https://flagcdn.com/be.svg' },
  { title: 'Belice', cdn: 'https://flagcdn.com/bz.svg' },
  { title: 'Benín', cdn: 'https://flagcdn.com/bj.svg' },
  { title: 'Bermudas', cdn: 'https://flagcdn.com/bm.svg' },
  { title: 'Bielorrusia', cdn: 'https://flagcdn.com/by.svg' },
  { title: 'Bolivia', cdn: 'https://flagcdn.com/bo.svg' },
  { title: 'Bosnia y Herzegovina', cdn: 'https://flagcdn.com/ba.svg' },
  { title: 'Botsuana', cdn: 'https://flagcdn.com/bw.svg' },
  { title: 'Brasil', cdn: 'https://flagcdn.com/br.svg' },
  { title: 'Brunéi', cdn: 'https://flagcdn.com/bn.svg' },
  { title: 'Bulgaria', cdn: 'https://flagcdn.com/bg.svg' },
  { title: 'Burkina Faso', cdn: 'https://flagcdn.com/bf.svg' },
  { title: 'Burundi', cdn: 'https://flagcdn.com/bi.svg' },
  { title: 'Bután', cdn: 'https://flagcdn.com/bt.svg' },
  { title: 'Cabo Verde', cdn: 'https://flagcdn.com/cv.svg' },
  { title: 'Camboya', cdn: 'https://flagcdn.com/kh.svg' },
  { title: 'Camerún', cdn: 'https://flagcdn.com/cm.svg' },
  { title: 'Canadá', cdn: 'https://flagcdn.com/ca.svg' },
  { title: 'Catar', cdn: 'https://flagcdn.com/qa.svg' },
  { title: 'Chad', cdn: 'https://flagcdn.com/td.svg' },
  { title: 'Chile', cdn: 'https://flagcdn.com/cl.svg' },
  { title: 'China', cdn: 'https://flagcdn.com/cn.svg' },
  { title: 'Chipre', cdn: 'https://flagcdn.com/cy.svg' },
  { title: 'Colombia', cdn: 'https://flagcdn.com/co.svg' },
  { title: 'Comoras', cdn: 'https://flagcdn.com/km.svg' },
  { title: 'Congo', cdn: 'https://flagcdn.com/cg.svg' },
  { title: 'Corea del Norte', cdn: 'https://flagcdn.com/kp.svg' },
  { title: 'Corea del Sur', cdn: 'https://flagcdn.com/kr.svg' },
  { title: 'Costa de Marfil', cdn: 'https://flagcdn.com/ci.svg' },
  { title: 'Costa Rica', cdn: 'https://flagcdn.com/cr.svg' },
  { title: 'Croacia', cdn: 'https://flagcdn.com/hr.svg' },
  { title: 'Cuba', cdn: 'https://flagcdn.com/cu.svg' },
  { title: 'Curazao', cdn: 'https://flagcdn.com/cw.svg' },
  { title: 'Dinamarca', cdn: 'https://flagcdn.com/dk.svg' },
  { title: 'Dominica', cdn: 'https://flagcdn.com/dm.svg' },
  { title: 'Ecuador', cdn: 'https://flagcdn.com/ec.svg' },
  { title: 'Egipto', cdn: 'https://flagcdn.com/eg.svg' },
  { title: 'El Salvador', cdn: 'https://flagcdn.com/sv.svg' },
  { title: 'Emiratos Árabes Unidos', cdn: 'https://flagcdn.com/ae.svg' },
  { title: 'Eritrea', cdn: 'https://flagcdn.com/er.svg' },
  { title: 'Eslovaquia', cdn: 'https://flagcdn.com/sk.svg' },
  { title: 'Eslovenia', cdn: 'https://flagcdn.com/si.svg' },
  { title: 'España', cdn: 'https://flagcdn.com/es.svg' },
  { title: 'Estados Unidos', cdn: 'https://flagcdn.com/us.svg' },
  { title: 'Estonia', cdn: 'https://flagcdn.com/ee.svg' },
  { title: 'Esuatini', cdn: 'https://flagcdn.com/sz.svg' },
  { title: 'Etiopía', cdn: 'https://flagcdn.com/et.svg' },
  { title: 'Filipinas', cdn: 'https://flagcdn.com/ph.svg' },
  { title: 'Finlandia', cdn: 'https://flagcdn.com/fi.svg' },
  { title: 'Fiyi', cdn: 'https://flagcdn.com/fj.svg' },
  { title: 'Francia', cdn: 'https://flagcdn.com/fr.svg' },
  { title: 'Gabón', cdn: 'https://flagcdn.com/ga.svg' },
  { title: 'Gambia', cdn: 'https://flagcdn.com/gm.svg' },
  { title: 'Georgia', cdn: 'https://flagcdn.com/ge.svg' },
  { title: 'Ghana', cdn: 'https://flagcdn.com/gh.svg' },
  { title: 'Gibraltar', cdn: 'https://flagcdn.com/gi.svg' },
  { title: 'Granada', cdn: 'https://flagcdn.com/gd.svg' },
  { title: 'Grecia', cdn: 'https://flagcdn.com/gr.svg' },
  { title: 'Groenlandia', cdn: 'https://flagcdn.com/gl.svg' },
  { title: 'Guadalupe', cdn: 'https://flagcdn.com/gp.svg' },
  { title: 'Guam', cdn: 'https://flagcdn.com/gu.svg' },
  { title: 'Guatemala', cdn: 'https://flagcdn.com/gt.svg' },
  { title: 'Guayana Francesa', cdn: 'https://flagcdn.com/gf.svg' },
  { title: 'Guernsey', cdn: 'https://flagcdn.com/gg.svg' },
  { title: 'Guinea', cdn: 'https://flagcdn.com/gn.svg' },
  { title: 'Guinea-Bisáu', cdn: 'https://flagcdn.com/gw.svg' },
  { title: 'Guinea Ecuatorial', cdn: 'https://flagcdn.com/gq.svg' },
  { title: 'Guyana', cdn: 'https://flagcdn.com/gy.svg' },
  { title: 'Haití', cdn: 'https://flagcdn.com/ht.svg' },
  { title: 'Honduras', cdn: 'https://flagcdn.com/hn.svg' },
  { title: 'Hong Kong', cdn: 'https://flagcdn.com/hk.svg' },
  { title: 'Hungría', cdn: 'https://flagcdn.com/hu.svg' },
  { title: 'India', cdn: 'https://flagcdn.com/in.svg' },
  { title: 'Indonesia', cdn: 'https://flagcdn.com/id.svg' },
  { title: 'Irak', cdn: 'https://flagcdn.com/iq.svg' },
  { title: 'Irán', cdn: 'https://flagcdn.com/ir.svg' },
  { title: 'Irlanda', cdn: 'https://flagcdn.com/ie.svg' },
  { title: 'Isla Bouvet', cdn: 'https://flagcdn.com/bv.svg' },
  { title: 'Isla de Man', cdn: 'https://flagcdn.com/im.svg' },
  { title: 'Isla Norfolk', cdn: 'https://flagcdn.com/nf.svg' },
  { title: 'Islandia', cdn: 'https://flagcdn.com/is.svg' },
  { title: 'Islas Åland', cdn: 'https://flagcdn.com/ax.svg' },
  { title: 'Islas Caimán', cdn: 'https://flagcdn.com/ky.svg' },
  { title: 'Islas Cocos', cdn: 'https://flagcdn.com/cc.svg' },
  { title: 'Islas Cook', cdn: 'https://flagcdn.com/ck.svg' },
  { title: 'Islas Feroe', cdn: 'https://flagcdn.com/fo.svg' },
  { title: 'Islas Georgias del Sur y Sandwich del Sur', cdn: 'https://flagcdn.com/gs.svg' },
  { title: 'Islas Heard y McDonald', cdn: 'https://flagcdn.com/hm.svg' },
  { title: 'Islas Malvinas', cdn: 'https://flagcdn.com/fk.svg' },
  { title: 'Islas Marianas del Norte', cdn: 'https://flagcdn.com/mp.svg' },
  { title: 'Islas Marshall', cdn: 'https://flagcdn.com/mh.svg' },
  { title: 'Islas Pitcairn', cdn: 'https://flagcdn.com/pn.svg' },
  { title: 'Islas Salomón', cdn: 'https://flagcdn.com/sb.svg' },
  { title: 'Islas Turcas y Caicos', cdn: 'https://flagcdn.com/tc.svg' },
  { title: 'Islas Vírgenes Británicas', cdn: 'https://flagcdn.com/vg.svg' },
  { title: 'Islas Vírgenes de los Estados Unidos', cdn: 'https://flagcdn.com/vi.svg' },
  { title: 'Israel', cdn: 'https://flagcdn.com/il.svg' },
  { title: 'Italia', cdn: 'https://flagcdn.com/it.svg' },
  { title: 'Jamaica', cdn: 'https://flagcdn.com/jm.svg' },
  { title: 'Japón', cdn: 'https://flagcdn.com/jp.svg' },
  { title: 'Jersey', cdn: 'https://flagcdn.com/je.svg' },
  { title: 'Jordania', cdn: 'https://flagcdn.com/jo.svg' },
  { title: 'Kazajistán', cdn: 'https://flagcdn.com/kz.svg' },
  { title: 'Kenia', cdn: 'https://flagcdn.com/ke.svg' },
  { title: 'Kirguistán', cdn: 'https://flagcdn.com/kg.svg' },
  { title: 'Kiribati', cdn: 'https://flagcdn.com/ki.svg' },
  { title: 'Kuwait', cdn: 'https://flagcdn.com/kw.svg' },
  { title: 'Laos', cdn: 'https://flagcdn.com/la.svg' },
  { title: 'Lesoto', cdn: 'https://flagcdn.com/ls.svg' },
  { title: 'Letonia', cdn: 'https://flagcdn.com/lv.svg' },
  { title: 'Líbano', cdn: 'https://flagcdn.com/lb.svg' },
  { title: 'Liberia', cdn: 'https://flagcdn.com/lr.svg' },
  { title: 'Libia', cdn: 'https://flagcdn.com/ly.svg' },
  { title: 'Liechtenstein', cdn: 'https://flagcdn.com/li.svg' },
  { title: 'Lituania', cdn: 'https://flagcdn.com/lt.svg' },
  { title: 'Luxemburgo', cdn: 'https://flagcdn.com/lu.svg' },
  { title: 'Macao', cdn: 'https://flagcdn.com/mo.svg' },
  { title: 'Madagascar', cdn: 'https://flagcdn.com/mg.svg' },
  { title: 'Malasia', cdn: 'https://flagcdn.com/my.svg' },
  { title: 'Malaui', cdn: 'https://flagcdn.com/mw.svg' },
  { title: 'Maldivas', cdn: 'https://flagcdn.com/mv.svg' },
  { title: 'Malí', cdn: 'https://flagcdn.com/ml.svg' },
  { title: 'Malta', cdn: 'https://flagcdn.com/mt.svg' },
  { title: 'Marruecos', cdn: 'https://flagcdn.com/ma.svg' },
  { title: 'Martinica', cdn: 'https://flagcdn.com/mq.svg' },
  { title: 'Mauricio', cdn: 'https://flagcdn.com/mu.svg' },
  { title: 'Mauritania', cdn: 'https://flagcdn.com/mr.svg' },
  { title: 'Mayotte', cdn: 'https://flagcdn.com/yt.svg' },
  { title: 'México', cdn: 'https://flagcdn.com/mx.svg' },
  { title: 'Micronesia', cdn: 'https://flagcdn.com/fm.svg' },
  { title: 'Moldavia', cdn: 'https://flagcdn.com/md.svg' },
  { title: 'Mónaco', cdn: 'https://flagcdn.com/mc.svg' },
  { title: 'Mongolia', cdn: 'https://flagcdn.com/mn.svg' },
  { title: 'Montenegro', cdn: 'https://flagcdn.com/me.svg' },
  { title: 'Montserrat', cdn: 'https://flagcdn.com/ms.svg' },
  { title: 'Mozambique', cdn: 'https://flagcdn.com/mz.svg' },
  { title: 'Myanmar', cdn: 'https://flagcdn.com/mm.svg' },
  { title: 'Namibia', cdn: 'https://flagcdn.com/na.svg' },
  { title: 'Nauru', cdn: 'https://flagcdn.com/nr.svg' },
  { title: 'Nepal', cdn: 'https://flagcdn.com/np.svg' },
  { title: 'Nicaragua', cdn: 'https://flagcdn.com/ni.svg' },
  { title: 'Níger', cdn: 'https://flagcdn.com/ne.svg' },
  { title: 'Nigeria', cdn: 'https://flagcdn.com/ng.svg' },
  { title: 'Niue', cdn: 'https://flagcdn.com/nu.svg' },
  { title: 'Noruega', cdn: 'https://flagcdn.com/no.svg' },
  { title: 'Nueva Caledonia', cdn: 'https://flagcdn.com/nc.svg' },
  { title: 'Nueva Zelanda', cdn: 'https://flagcdn.com/nz.svg' },
  { title: 'Omán', cdn: 'https://flagcdn.com/om.svg' },
  { title: 'Países Bajos', cdn: 'https://flagcdn.com/nl.svg' },
  { title: 'Pakistán', cdn: 'https://flagcdn.com/pk.svg' },
  { title: 'Palaos', cdn: 'https://flagcdn.com/pw.svg' },
  { title: 'Palestina', cdn: 'https://flagcdn.com/ps.svg' },
  { title: 'Panamá', cdn: 'https://flagcdn.com/pa.svg' },
  { title: 'Papúa Nueva Guinea', cdn: 'https://flagcdn.com/pg.svg' },
  { title: 'Paraguay', cdn: 'https://flagcdn.com/py.svg' },
  { title: 'Perú', cdn: 'https://flagcdn.com/pe.svg' },
  { title: 'Polinesia Francesa', cdn: 'https://flagcdn.com/pf.svg' },
  { title: 'Polonia', cdn: 'https://flagcdn.com/pl.svg' },
  { title: 'Portugal', cdn: 'https://flagcdn.com/pt.svg' },
  { title: 'Puerto Rico', cdn: 'https://flagcdn.com/pr.svg' },
  { title: 'Reino Unido', cdn: 'https://flagcdn.com/gb.svg' },
  { title: 'República Centroafricana', cdn: 'https://flagcdn.com/cf.svg' },
  { title: 'República Checa', cdn: 'https://flagcdn.com/cz.svg' },
  { title: 'República del Congo', cdn: 'https://flagcdn.com/cd.svg' },
  { title: 'República Dominicana', cdn: 'https://flagcdn.com/do.svg' },
  { title: 'República de Macedonia del Norte', cdn: 'https://flagcdn.com/mk.svg' },
  { title: 'Reunión', cdn: 'https://flagcdn.com/re.svg' },
  { title: 'Rumania', cdn: 'https://flagcdn.com/ro.svg' },
  { title: 'Rusia', cdn: 'https://flagcdn.com/ru.svg' },
  { title: 'Ruanda', cdn: 'https://flagcdn.com/rw.svg' },
  { title: 'Sahara Occidental', cdn: 'https://flagcdn.com/eh.svg' },
  { title: 'Samoa', cdn: 'https://flagcdn.com/ws.svg' },
  { title: 'Samoa Americana', cdn: 'https://flagcdn.com/as.svg' },
  { title: 'San Bartolomé', cdn: 'https://flagcdn.com/bl.svg' },
  { title: 'San Cristóbal y Nieves', cdn: 'https://flagcdn.com/kn.svg' },
  { title: 'San Marino', cdn: 'https://flagcdn.com/sm.svg' },
  { title: 'San Martín', cdn: 'https://flagcdn.com/mf.svg' },
  { title: 'San Pedro y Miquelón', cdn: 'https://flagcdn.com/pm.svg' },
  { title: 'San Vicente y las Granadinas', cdn: 'https://flagcdn.com/vc.svg' },
  { title: 'Santa Elena', cdn: 'https://flagcdn.com/sh.svg' },
  { title: 'Santa Lucía', cdn: 'https://flagcdn.com/lc.svg' },
  { title: 'Santo Tomé y Príncipe', cdn: 'https://flagcdn.com/st.svg' },
  { title: 'Senegal', cdn: 'https://flagcdn.com/sn.svg' },
  { title: 'Serbia', cdn: 'https://flagcdn.com/rs.svg' },
  { title: 'Seychelles', cdn: 'https://flagcdn.com/sc.svg' },
  { title: 'Sierra Leona', cdn: 'https://flagcdn.com/sl.svg' },
  { title: 'Singapur', cdn: 'https://flagcdn.com/sg.svg' },
  { title: 'Sint Maarten', cdn: 'https://flagcdn.com/sx.svg' },
  { title: 'Siria', cdn: 'https://flagcdn.com/sy.svg' },
  { title: 'Somalia', cdn: 'https://flagcdn.com/so.svg' },
  { title: 'Sri Lanka', cdn: 'https://flagcdn.com/lk.svg' },
  { title: 'Sudáfrica', cdn: 'https://flagcdn.com/za.svg' },
  { title: 'Sudán', cdn: 'https://flagcdn.com/sd.svg' },
  { title: 'Sudán del Sur', cdn: 'https://flagcdn.com/ss.svg' },
  { title: 'Suecia', cdn: 'https://flagcdn.com/se.svg' },
  { title: 'Suiza', cdn: 'https://flagcdn.com/ch.svg' },
  { title: 'Surinam', cdn: 'https://flagcdn.com/sr.svg' },
  { title: 'Svalbard y Jan Mayen', cdn: 'https://flagcdn.com/sj.svg' },
  { title: 'Tailandia', cdn: 'https://flagcdn.com/th.svg' },
  { title: 'Taiwán', cdn: 'https://flagcdn.com/tw.svg' },
  { title: 'Tanzania', cdn: 'https://flagcdn.com/tz.svg' },
  { title: 'Tayikistán', cdn: 'https://flagcdn.com/tj.svg' },
  { title: 'Territorio Británico del Océano Índico', cdn: 'https://flagcdn.com/io.svg' },
  { title: 'Territorios Australes Franceses', cdn: 'https://flagcdn.com/tf.svg' },
  { title: 'Timor Oriental', cdn: 'https://flagcdn.com/tl.svg' },
  { title: 'Togo', cdn: 'https://flagcdn.com/tg.svg' },
  { title: 'Tokelau', cdn: 'https://flagcdn.com/tk.svg' },
  { title: 'Tonga', cdn: 'https://flagcdn.com/to.svg' },
  { title: 'Trinidad y Tobago', cdn: 'https://flagcdn.com/tt.svg' },
  { title: 'Túnez', cdn: 'https://flagcdn.com/tn.svg' },
  { title: 'Turkmenistán', cdn: 'https://flagcdn.com/tm.svg' },
  { title: 'Turquía', cdn: 'https://flagcdn.com/tr.svg' },
  { title: 'Tuvalu', cdn: 'https://flagcdn.com/tv.svg' },
  { title: 'Ucrania', cdn: 'https://flagcdn.com/ua.svg' },
  { title: 'Uganda', cdn: 'https://flagcdn.com/ug.svg' },
  { title: 'Uruguay', cdn: 'https://flagcdn.com/uy.svg' },
  { title: 'Uzbekistán', cdn: 'https://flagcdn.com/uz.svg' },
  { title: 'Vanuatu', cdn: 'https://flagcdn.com/vu.svg' },
  { title: 'Vaticano', cdn: 'https://flagcdn.com/va.svg' },
  { title: 'Venezuela', cdn: 'https://flagcdn.com/ve.svg' },
  { title: 'Vietnam', cdn: 'https://flagcdn.com/vn.svg' },
  { title: 'Wallis y Futuna', cdn: 'https://flagcdn.com/wf.svg' },
  { title: 'Yemen', cdn: 'https://flagcdn.com/ye.svg' },
  { title: 'Yibuti', cdn: 'https://flagcdn.com/dj.svg' },
  { title: 'Zambia', cdn: 'https://flagcdn.com/zm.svg' },
  { title: 'Zimbabue', cdn: 'https://flagcdn.com/zw.svg' }
];

export const countriesWithLabelId = [
  { label: 'Afganistán', id: 'Afganistán' },
  { label: 'Albania', id: 'Albania' },
  { label: 'Alemania', id: 'Alemania' },
  { label: 'Andorra', id: 'Andorra' },
  { label: 'Angola', id: 'Angola' },
  { label: 'Anguila', id: 'Anguila' },
  { label: 'Antártida', id: 'Antártida' },
  { label: 'Antigua y Barbuda', id: 'Antigua y Barbuda' },
  { label: 'Arabia Saudita', id: 'Arabia Saudita' },
  { label: 'Argelia', id: 'Argelia' },
  { label: 'Argentina', id: 'Argentina' },
  { label: 'Armenia', id: 'Armenia' },
  { label: 'Aruba', id: 'Aruba' },
  { label: 'Australia', id: 'Australia' },
  { label: 'Austria', id: 'Austria' },
  { label: 'Azerbaiyán', id: 'Azerbaiyán' },
  { label: 'Bahamas', id: 'Bahamas' },
  { label: 'Bahrein', id: 'Bahrein' },
  { label: 'Bangladesh', id: 'Bangladesh' },
  { label: 'Barbados', id: 'Barbados' },
  { label: 'Bélgica', id: 'Bélgica' },
  { label: 'Belice', id: 'Belice' },
  { label: 'Benín', id: 'Benín' },
  { label: 'Bermudas', id: 'Bermudas' },
  { label: 'Bielorrusia', id: 'Bielorrusia' },
  { label: 'Bolivia', id: 'Bolivia' },
  { label: 'Bosnia y Herzegovina', id: 'Bosnia y Herzegovina' },
  { label: 'Botsuana', id: 'Botsuana' },
  { label: 'Brasil', id: 'Brasil' },
  { label: 'Brunéi', id: 'Brunéi' },
  { label: 'Bulgaria', id: 'Bulgaria' },
  { label: 'Burkina Faso', id: 'Burkina Faso' },
  { label: 'Burundi', id: 'Burundi' },
  { label: 'Bután', id: 'Bután' },
  { label: 'Cabo Verde', id: 'Cabo Verde' },
  { label: 'Camboya', id: 'Camboya' },
  { label: 'Camerún', id: 'Camerún' },
  { label: 'Canadá', id: 'Canadá' },
  { label: 'Catar', id: 'Catar' },
  { label: 'Chad', id: 'Chad' },
  { label: 'Chile', id: 'Chile' },
  { label: 'China', id: 'China' },
  { label: 'Chipre', id: 'Chipre' },
  { label: 'Colombia', id: 'Colombia' },
  { label: 'Comoras', id: 'Comoras' },
  { label: 'Congo', id: 'Congo' },
  { label: 'Corea del Norte', id: 'Corea del Norte' },
  { label: 'Corea del Sur', id: 'Corea del Sur' },
  { label: 'Costa de Marfil', id: 'Costa de Marfil' },
  { label: 'Costa Rica', id: 'Costa Rica' },
  { label: 'Croacia', id: 'Croacia' },
  { label: 'Cuba', id: 'Cuba' },
  { label: 'Curazao', id: 'Curazao' },
  { label: 'Dinamarca', id: 'Dinamarca' },
  { label: 'Dominica', id: 'Dominica' },
  { label: 'Ecuador', id: 'Ecuador' },
  { label: 'Egipto', id: 'Egipto' },
  { label: 'El Salvador', id: 'El Salvador' },
  { label: 'Emiratos Árabes Unidos', id: 'Emiratos Árabes Unidos' },
  { label: 'Eritrea', id: 'Eritrea' },
  { label: 'Eslovaquia', id: 'Eslovaquia' },
  { label: 'Eslovenia', id: 'Eslovenia' },
  { label: 'España', id: 'España' },
  { label: 'Estados Unidos', id: 'Estados Unidos' },
  { label: 'Estonia', id: 'Estonia' },
  { label: 'Esuatini', id: 'Esuatini' },
  { label: 'Etiopía', id: 'Etiopía' },
  { label: 'Filipinas', id: 'Filipinas' },
  { label: 'Finlandia', id: 'Finlandia' },
  { label: 'Fiyi', id: 'Fiyi' },
  { label: 'Francia', id: 'Francia' },
  { label: 'Gabón', id: 'Gabón' },
  { label: 'Gambia', id: 'Gambia' },
  { label: 'Georgia', id: 'Georgia' },
  { label: 'Ghana', id: 'Ghana' },
  { label: 'Gibraltar', id: 'Gibraltar' },
  { label: 'Granada', id: 'Granada' },
  { label: 'Grecia', id: 'Grecia' },
  { label: 'Groenlandia', id: 'Groenlandia' },
  { label: 'Guadalupe', id: 'Guadalupe' },
  { label: 'Guam', id: 'Guam' },
  { label: 'Guatemala', id: 'Guatemala' },
  { label: 'Guayana Francesa', id: 'Guayana Francesa' },
  { label: 'Guernsey', id: 'Guernsey' },
  { label: 'Guinea', id: 'Guinea' },
  { label: 'Guinea-Bisáu', id: 'Guinea-Bisáu' },
  { label: 'Guinea Ecuatorial', id: 'Guinea Ecuatorial' },
  { label: 'Guyana', id: 'Guyana' },
  { label: 'Haití', id: 'Haití' },
  { label: 'Honduras', id: 'Honduras' },
  { label: 'Hong Kong', id: 'Hong Kong' },
  { label: 'Hungría', id: 'Hungría' },
  { label: 'India', id: 'India' },
  { label: 'Indonesia', id: 'Indonesia' },
  { label: 'Irak', id: 'Irak' },
  { label: 'Irán', id: 'Irán' },
  { label: 'Irlanda', id: 'Irlanda' },
  { label: 'Isla Bouvet', id: 'Isla Bouvet' },
  { label: 'Isla de Man', id: 'Isla de Man' },
  { label: 'Isla Norfolk', id: 'Isla Norfolk' },
  { label: 'Islandia', id: 'Islandia' },
  { label: 'Islas Åland', id: 'Islas Åland' },
  { label: 'Islas Caimán', id: 'Islas Caimán' },
  { label: 'Islas Cocos', id: 'Islas Cocos' },
  { label: 'Islas Cook', id: 'Islas Cook' },
  { label: 'Islas Feroe', id: 'Islas Feroe' },
  { label: 'Islas Georgias del Sur y Sandwich del Sur', id: 'Islas Georgias del Sur y Sandwich del Sur' },
  { label: 'Islas Heard y McDonald', id: 'Islas Heard y McDonald' },
  { label: 'Islas Malvinas', id: 'Islas Malvinas' },
  { label: 'Islas Marianas del Norte', id: 'Islas Marianas del Norte' },
  { label: 'Islas Marshall', id: 'Islas Marshall' },
  { label: 'Islas Pitcairn', id: 'Islas Pitcairn' },
  { label: 'Islas Salomón', id: 'Islas Salomón' },
  { label: 'Islas Turcas y Caicos', id: 'Islas Turcas y Caicos' },
  { label: 'Islas Vírgenes Británicas', id: 'Islas Vírgenes Británicas' },
  { label: 'Islas Vírgenes de los Estados Unidos', id: 'Islas Vírgenes de los Estados Unidos' },
  { label: 'Israel', id: 'Israel' },
  { label: 'Italia', id: 'Italia' },
  { label: 'Jamaica', id: 'Jamaica' },
  { label: 'Japón', id: 'Japón' },
  { label: 'Jersey', id: 'Jersey' },
  { label: 'Jordania', id: 'Jordania' },
  { label: 'Kazajistán', id: 'Kazajistán' },
  { label: 'Kenia', id: 'Kenia' },
  { label: 'Kirguistán', id: 'Kirguistán' },
  { label: 'Kiribati', id: 'Kiribati' },
  { label: 'Kuwait', id: 'Kuwait' },
  { label: 'Laos', id: 'Laos' },
  { label: 'Lesoto', id: 'Lesoto' },
  { label: 'Letonia', id: 'Letonia' },
  { label: 'Líbano', id: 'Líbano' },
  { label: 'Liberia', id: 'Liberia' },
  { label: 'Libia', id: 'Libia' },
  { label: 'Liechtenstein', id: 'Liechtenstein' },
  { label: 'Lituania', id: 'Lituania' },
  { label: 'Luxemburgo', id: 'Luxemburgo' },
  { label: 'Macao', id: 'Macao' },
  { label: 'Madagascar', id: 'Madagascar' },
  { label: 'Malasia', id: 'Malasia' },
  { label: 'Malaui', id: 'Malaui' },
  { label: 'Maldivas', id: 'Maldivas' },
  { label: 'Malí', id: 'Malí' },
  { label: 'Malta', id: 'Malta' },
  { label: 'Marruecos', id: 'Marruecos' },
  { label: 'Martinica', id: 'Martinica' },
  { label: 'Mauricio', id: 'Mauricio' },
  { label: 'Mauritania', id: 'Mauritania' },
  { label: 'Mayotte', id: 'Mayotte' },
  { label: 'México', id: 'México' },
  { label: 'Micronesia', id: 'Micronesia' },
  { label: 'Moldavia', id: 'Moldavia' },
  { label: 'Mónaco', id: 'Mónaco' },
  { label: 'Mongolia', id: 'Mongolia' },
  { label: 'Montenegro', id: 'Montenegro' },
  { label: 'Montserrat', id: 'Montserrat' },
  { label: 'Mozambique', id: 'Mozambique' },
  { label: 'Myanmar', id: 'Myanmar' },
  { label: 'Namibia', id: 'Namibia' },
  { label: 'Nauru', id: 'Nauru' },
  { label: 'Nepal', id: 'Nepal' },
  { label: 'Nicaragua', id: 'Nicaragua' },
  { label: 'Níger', id: 'Níger' },
  { label: 'Nigeria', id: 'Nigeria' },
  { label: 'Niue', id: 'Niue' },
  { label: 'Noruega', id: 'Noruega' },
  { label: 'Nueva Caledonia', id: 'Nueva Caledonia' },
  { label: 'Nueva Zelanda', id: 'Nueva Zelanda' },
  { label: 'Omán', id: 'Omán' },
  { label: 'Países Bajos', id: 'Países Bajos' },
  { label: 'Pakistán', id: 'Pakistán' },
  { label: 'Palaos', id: 'Palaos' },
  { label: 'Palestina', id: 'Palestina' },
  { label: 'Panamá', id: 'Panamá' },
  { label: 'Papúa Nueva Guinea', id: 'Papúa Nueva Guinea' },
  { label: 'Paraguay', id: 'Paraguay' },
  { label: 'Perú', id: 'Perú' },
  { label: 'Polinesia Francesa', id: 'Polinesia Francesa' },
  { label: 'Polonia', id: 'Polonia' },
  { label: 'Portugal', id: 'Portugal' },
  { label: 'Puerto Rico', id: 'Puerto Rico' },
  { label: 'Reino Unido', id: 'Reino Unido' },
  { label: 'República Centroafricana', id: 'República Centroafricana' },
  { label: 'República Checa', id: 'República Checa' },
  { label: 'República del Congo', id: 'República del Congo' },
  { label: 'República Dominicana', id: 'República Dominicana' },
  { label: 'República de Macedonia del Norte', id: 'República de Macedonia del Norte' },
  { label: 'Reunión', id: 'Reunión' },
  { label: 'Rumania', id: 'Rumania' },
  { label: 'Rusia', id: 'Rusia' },
  { label: 'Ruanda', id: 'Ruanda' },
  { label: 'Sahara Occidental', id: 'Sahara Occidental' },
  { label: 'Samoa', id: 'Samoa' },
  { label: 'Samoa Americana', id: 'Samoa Americana' },
  { label: 'San Bartolomé', id: 'San Bartolomé' },
  { label: 'San Cristóbal y Nieves', id: 'San Cristóbal y Nieves' },
  { label: 'San Marino', id: 'San Marino' },
  { label: 'San Martín', id: 'San Martín' },
  { label: 'San Pedro y Miquelón', id: 'San Pedro y Miquelón' },
  { label: 'San Vicente y las Granadinas', id: 'San Vicente y las Granadinas' },
  { label: 'Santa Elena', id: 'Santa Elena' },
  { label: 'Santa Lucía', id: 'Santa Lucía' },
  { label: 'Santo Tomé y Príncipe', id: 'Santo Tomé y Príncipe' },
  { label: 'Senegal', id: 'Senegal' },
  { label: 'Serbia', id: 'Serbia' },
  { label: 'Seychelles', id: 'Seychelles' },
  { label: 'Sierra Leona', id: 'Sierra Leona' },
  { label: 'Singapur', id: 'Singapur' },
  { label: 'Sint Maarten', id: 'Sint Maarten' },
  { label: 'Siria', id: 'Siria' },
  { label: 'Somalia', id: 'Somalia' },
  { label: 'Sri Lanka', id: 'Sri Lanka' },
  { label: 'Sudáfrica', id: 'Sudáfrica' },
  { label: 'Sudán', id: 'Sudán' },
  { label: 'Sudán del Sur', id: 'Sudán del Sur' },
  { label: 'Suecia', id: 'Suecia' },
  { label: 'Suiza', id: 'Suiza' },
  { label: 'Surinam', id: 'Surinam' },
  { label: 'Svalbard y Jan Mayen', id: 'Svalbard y Jan Mayen' },
  { label: 'Tailandia', id: 'Tailandia' },
  { label: 'Taiwán', id: 'Taiwán' },
  { label: 'Tanzania', id: 'Tanzania' },
  { label: 'Tayikistán', id: 'Tayikistán' },
  { label: 'Territorio Británico del Océano Índico', id: 'Territorio Británico del Océano Índico' },
  { label: 'Territorios Australes Franceses', id: 'Territorios Australes Franceses' },
  { label: 'Timor Oriental', id: 'Timor Oriental' },
  { label: 'Togo', id: 'Togo' },
  { label: 'Tokelau', id: 'Tokelau' },
  { label: 'Tonga', id: 'Tonga' },
  { label: 'Trinidad y Tobago', id: 'Trinidad y Tobago' },
  { label: 'Túnez', id: 'Túnez' },
  { label: 'Turkmenistán', id: 'Turkmenistán' },
  { label: 'Turquía', id: 'Turquía' },
  { label: 'Tuvalu', id: 'Tuvalu' },
  { label: 'Ucrania', id: 'Ucrania' },
  { label: 'Uganda', id: 'Uganda' },
  { label: 'Uruguay', id: 'Uruguay' },
  { label: 'Uzbekistán', id: 'Uzbekistán' },
  { label: 'Vanuatu', id: 'Vanuatu' },
  { label: 'Vaticano', id: 'Vaticano' },
  { label: 'Venezuela', id: 'Venezuela' },
  { label: 'Vietnam', id: 'Vietnam' },
  { label: 'Wallis y Futuna', id: 'Wallis y Futuna' },
  { label: 'Yemen', id: 'Yemen' },
  { label: 'Yibuti', id: 'Yibuti' },
  { label: 'Zambia', id: 'Zambia' },
  { label: 'Zimbabue', id: 'Zimbabue' }
];